server:
  port: 8080
spring:
  config:
    import: classpath:quickstart.properties
  data:
    mongodb:
      port: 27017
      username: admin
      password: admin
      database: tacoclouddb
      host: localhost
      authentication-database: admin
      auto-index-creation: true
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
